---
title: Freelancer
email: your-email@domain.com
url: https://heydavid-dev.github.io
baseurl: "/freelancer-staging-1-13"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: your keywords, separated by commas
skills: Web Developer - Graphic Artist - User Experience Designer
meta-author: LastName FirstName
google-verify: ''
bing-verify: ''
disqus-shortname: myshortname
color:
  primary: 18bc9c
  secondary: 2c3e50
  secondary-dark: '233140'
about:
  title: About
  first-description: Freelancer is a free bootstrap theme created by Start Bootstrap.
    The download includes the complete source files including HTML, CSS, and JavaScript
    as well as optional LESS stylesheets for easy customization.
  second-description: Whether you're a student looking to showcase your work, a professional
    looking to attract clients, or a graphic artist looking to share your projects,
    this template is the perfect starting point!
  button-url: https://github.com/jeromelachaud/freelancer-theme
  button-text: Download Theme
contact:
  title: Contact Me
portfolio:
  title: Portfolio
footer:
  location: Location
  credits: Credits
social-list:
- title: envelope
  url: mailto:someone@example.com
- title: phone
  url: tel:123-456-7890
- title: whatsapp
  url: https://wa.me/1234567890
- title: map-marker
  url: https://goo.gl/maps/cb49MvbmdRehc7Zf9
- title: twitter
  url: https://twitter.com
address: 3481 Melrose Place, Beverly Hills, CA 90210
credits: Freelancer is a free to use, open source theme, created by Start Bootstrap.
markdown: kramdown
permalink: pretty
